apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcc-stores
  labels:
    app: pcc-stores
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pcc-stores
  template:
    metadata:
      labels:
        app: pcc-stores
    spec:
      containers:
        - name: pcc-stores
          image: diogojms/pcc_stores:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://DriveCleaner:DriveCleanerG7@cluster0.bj3pzfe.mongodb.net/Stores"
            - name: SECRET
              value: "jfcnbjsnwdelwjcnewdlejbsfew"
            - name: LOGS_URI
              value: "guest:guest@localhost:5672/"
