apiVersion: v1
kind: Service
metadata:
  name: pcc-stores
  labels:
    app: pcc-stores
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8086
  selector:
    app: pcc-stores
  sessionAffinity: None
